"use client";
import BottomNavigation from "@/app/components/BottomNavigation";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { FaBook, FaDownload } from "react-icons/fa";
import { Bell, Users, LogOut } from "lucide-react";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const hideBottomNav = ["/", "/login", "/signup", "/admin"].includes(pathname);
  const hideSideBar = ["/login", "/signup", "/user"].includes(pathname);
  const isAdmin = pathname.includes("/admin");
  function Sidebar({ children }) {
    const items = [
      { label: "Users", icon: <Users />, href: "/admin/dashboard" },
      { label: "Auth", icon: <LogOut />, href: "/admin/auth" },
      { label: "Notifications", icon: <Bell />, href: "/admin/notifications" },
      { label: "Courses", icon: <FaBook />, href: "/admin/courses" },
      { label: "Export", icon: <FaDownload />, href: "/admin/export" },
    ];

    return (
      <div className="flex h-screen">
        <aside className="w-64 bg-white border-r p-4">
          <h2 className="text-xl font-bold mb-6">Happy Admin</h2>
          {items.map((item) => (
            <Link
              key={item.href}
              href={item.href}
              className="flex items-center gap-2 py-2 px-4 hover:bg-gray-100 rounded-lg"
            >
              {item.icon} <span>{item.label}</span>
            </Link>
          ))}
        </aside>
        <main className="flex-1 p-6 overflow-y-auto">{children}</main>
      </div>
    );
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isAdmin ? (
          <Sidebar>{children}</Sidebar>
        ) : (
          <>
            {children}
            {!hideBottomNav && <BottomNavigation />}
          </>
        )}
      </body>
    </html>
  );
}
